# Generated by Django 4.2.1 on 2023-10-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
