# Generated by Django 4.2.1 on 2023-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
